var researcherList = [
  {
    name_en: "",
    name_th: "ผศ.ดร. ศรินยา สนิทวงศ์ ณ อยุธยา",
    educate: "ปริญญาเอก",
    posi: "คณบดี คณะพาณิชยนาวีนานาชาติ",
    major : "Ph.D. Civil Engineering and Environment, University of Southampton",
    dept : "วศ.ม. วิศวกรรมโยธา มหาวิทยาลัยเชียงใหม่",
    article: 3,
    project: 3,
    award: 0,
    img: "../img/t/index.jpg",
  },
  {
    name_en: "",
    name_th: "รศ.ดร. ธัญญะ เกียรติวัฒน์",
    educate: "ปริญญาเอก",
    posi: "ผู้ช่วยศาสตราจารย์",
    major : "วิศวกรรมต่อเรือและวิศวกรรมสมุทรศาสตร์",
    dept : "วิศวกรรมต่อเรือและวิศวกรรมสมุทรศาสตร์",
    article: 3,
    project: 3,
    award: 0,
    img: "../img/t/index2.jpg",
  },
  {
    name_en: "",
    name_th: "พลเรือเอก สุพิทย์ อำนวย",
    educate: "",
    posi: "ผู้ทรงคุณวุฒิ",
    major : "",
    dept : "-",
    article: 0,
    project: 0,
    award: 0,
    img: "../img/t/index3.jpg",
  },
  {
    name_en: "",
    name_th: "พลเรือเอก สุรินทร์ เริงอารมณ์",
    educate: "",
    posi: "ผู้ทรงคุณวุฒิ",
    major : "",
    dept : "-",
    article: 0,
    project: 0,
    award: 0,
    img: "../img/t/index4.jpg",
  },
  {
    name_en: "",
    name_th: "พลเรือเอก สมใจ วัฒนโยธิน",
    educate: "",
    posi: "ผู้ทรงคุณวุฒิ",
    major : "",
    dept : "-",
    article: 0,
    project: 0,
    award: 0,
    img: "../img/t/index5.jpg",
  },
  {
    name_en: "",
    name_th: "เรือเอก นคร น กุลศรีรัตน์",
    educate: "",
    posi: "ผู้ทรงคุณวุฒิ",
    major : "",
    dept : "-",
    article: 0,
    project: 0,
    award: 0,
    img: "../img/t/index7.jpg",
  },
  {
    name_en: "",
    name_th: "พันจ่าเอก พีระ ฐิตตะคุโน",
    educate: "",
    posi: "ผู้ทรงคุณวุฒิ",
    major : "",
    dept : "-",
    article: 0,
    project: 0,
    award: 0,
    img: "../img/t/index8.jpg",
  },
  {
    name_en: "",
    name_th: "ผศ.ดร. ชาตินักรบ แสงสว่าง",
    educate: "",
    posi: "รองคณบดีฝ่ายพัฒนาองค์กร",
    major : "วศ.บ. วิศวกรรมอุตสาหการ มหาวิทยาลัยขอนแก่น",
    dept : "",
    article: 0,
    project: 0,
    award: 0,
    img: "../img/t/index10.jpg",
  },
  {
    name_en: "",
    name_th: "ผศ.ดร. แพรวพรรณ ออเรืองเอก",
    educate: "",
    posi: "รองคณบดีฝ่ายการคลังและพัสดุ",
    major : "Ph.D. Economics International Program สถาบันบัณฑิตพัฒนบริหารศาสตร์",
    dept : "",
    article: 0,
    project: 0,
    award: 0,
    img: "../img/t/index11.jpg",
  },
  {
    name_en: "",
    name_th: "ผศ.ดร. แพรวพรรณ ออเรืองเอก",
    educate: "",
    posi: "รองคณบดีฝ่ายกิจการพิเศษ",
    major : "D.Eng. Area of Specialization : Integrated Coastal Zone Management, The Asian Institute of Technology (AIT)",
    dept : "",
    article: 0,
    project: 0,
    award: 0,
    img: "../img/t/index12.jpg",
  },
  {
    name_en: "",
    name_th: "ผศ.ดร. พรรณศักดิ์ เอี่ยมรักษา",
    educate: "",
    posi: "รองคณบดีฝ่ายวิชาการและพัฒนานิสิต",
    major : "วท.บ. ฟิสิกส์ประยุกต์ สถาบันเทคโนโลยีพระจอมเกล้าเจ้าคุณทหารลาดกระบัง",
    dept : "",
    article: 0,
    project: 0,
    award: 0,
    img: "../img/t/index13.jpg",
  },
  {
    name_en: "",
    name_th: "ผศ.ดร. รัฐกฤต เรียบร้อย",
    educate: "",
    posi: "รองคณบดีหน่วยวิจัยและนวัตกรรม",
    major : "วศ.บ. วิศวกรรมต่อเรือและเครื่องกลเรือ มหาวิทยาลัยเกษตรศาสตร์",
    dept : "",
    article: 0,
    project: 0,
    award: 0,
    img: "../img/t/index14.jpg",
  },
  {
    name_en: "",
    name_th: "ผศ.ดร. ประชากร แก้วเขียว",
    educate: "",
    posi: "รองคณบดีฝ่ายกายภาพและเทคโนโลยีดิจิทัล",
    major : "วศ.บ. วิศวกรรมต่อเรือและเครื่องกลเรือ มหาวิทยาลัยเกษตรศาสตร์",
    dept : "",
    article: 0,
    project: 0,
    award: 0,
    img: "../img/t/index15.jpg",
  },
  {
    name_en: "",
    name_th: "นางสาว ศลิษา วังทอง",
    educate: "",
    posi: "ประธานหลักสูตร วท.บ. วิทยาศาสตร์การเดินเรือ หัวหน้าภาควิชาวิทยาการเดินเรือ และโลจิสติกส์ทางทะเล รักษาการผู้ช่วยคณบดีฝ่ายวิชาการ",
    major : "วท.บ. ฟิสิกส์ประยุกต์ สถาบันเทคโนโลยีพระจอมเกล้าเจ้าคุณทหารลาดกระบัง",
    dept : "",
    article: 0,
    project: 0,
    award: 0,
    img: "../img/t/index16.jpg",
  },
  {
    name_en: "",
    name_th: "ดร. ไพรีพินาศ พิมพิสาร",
    educate: "",
    posi: "หัวหน้าภาควิชาวิศวกรรมทางทะเล",
    major : "วศ.บ. วิศวกรรมไฟฟ้าเครื่องกลการผลิต มหาวิทยาลัยเกษตรศาสตร์",
    dept : "",
    article: 0,
    project: 0,
    award: 0,
    img: "../img/t/index17.jpg",
  },
  {
    name_en: "",
    name_th: "รศ.ดร. ธีร์ เชาวนนทปัญญา",
    educate: "",
    posi: "ผู้ช่วยคณบดีฝ่ายวิเทศสัมพันธ์",
    major : "วศ.บ. วิศวกรรมเครื่องกล มหาวิทยาลัยเทคโนโลยีพระจอมเกล้าธนบุรี",
    dept : "",
    article: 0,
    project: 0,
    award: 0,
    img: "../img/t/index18.jpg",
  },
  {
    name_en: "",
    name_th: "นาย ศิวกร สุขประเสริฐชัย",
    educate: "",
    posi: "ผู้ช่วยคณบดีหน่วยวิจัยและนวัตกรรม",
    major : "วท.บ. ฟิสิกส์ประยุกต์-เครื่องมือวิทยาศาสตร์และอุตสาหกรรม สถาบันเทคโนโลยีพระจอมเกล้าเจ้าคุณทหารลาดกระบัง",
    dept : "",
    article: 0,
    project: 0,
    award: 0,
    img: "../img/t/index19.jpg",
  },
  ///
  {
    name_en: "",
    name_th: "นาย ศิวกร สุขประเสริฐชัย",
    educate: "",
    posi: "ผู้ช่วยคณบดีหน่วยวิจัยและนวัตกรรม",
    major : "วท.บ. ฟิสิกส์ประยุกต์-เครื่องมือวิทยาศาสตร์และอุตสาหกรรม สถาบันเทคโนโลยีพระจอมเกล้าเจ้าคุณทหารลาดกระบัง",
    dept : "",
    article: 0,
    project: 0,
    award: 0,
    img: "../img/t/index20.jpg",
  },
  {
    name_en: "",
    name_th: "นางสาว บุญจิรา ปั่นทอง",
    educate: "",
    posi: "หัวหน้าสำนักงานเลขานุการ",
    major : "กศ.บ. เทคโนโลยีทางการศึกษา มหาวิทยาลัยบูรพา",
    dept : "",
    article: 0,
    project: 0,
    award: 0,
    img: "../img/t/index20.jpg",
  },
  {
    name_en: "",
    name_th: "นางสาว ริสา ฟองสายชล",
    educate: "",
    posi: "ผู้ช่วยคณบดีฝ่ายอำนวยการ",
    major : "วท.บ. ภูมิศาสตร์ มหาวิทยาลัยบูรพา",
    dept : "",
    article: 0,
    project: 0,
    award: 0,
    img: "../img/t/index21.jpg",
  },
  {
    name_en: "",
    name_th: "นางสาว จิรัชยา ทองเสน",
    educate: "",
    posi: "นักวิชาการเงินและบัญชี ชำนาญการ [ หัวหน้างานคลังและพัสดุ ]",
    major : "บช.บ. การบัญชี มหาวิทยาลัยสยาม",
    dept : "",
    article: 0,
    project: 0,
    award: 0,
    img: "../img/t/index22.jpg",
  },
  {
    name_en: "",
    name_th: "นางสาว ณัฐปภัสษ์ เล่าเฮ้ย",
    educate: "",
    posi: "นักวิชาการศึกษา ชำนาญการ[ หัวหน้างานบริการการศึกษาและพัฒนานิสิต ]",
    major : "ศศ.บ. การจัดการทั่วไป (การตลาด) สถาบันราชภัฏสวนสุนันทา",
    dept : "",
    article: 0,
    project: 0,
    award: 0,
    img: "../img/t/index23.jpg",
  },
  {
    name_en: "",
    name_th: "นางสาว โสภณา คุณุทัย",
    educate: "",
    posi: "เจ้าหน้าที่บริหารงานทั่วไป ชำนาญการ [ หัวหน้างานบริหารและพัฒนาองค์กร ]",
    major : "บช.บ. การบัญชี มหาวิทยาลัยสยาม",
    dept : "",
    article: 0,
    project: 0,
    award: 0,
    img: "../img/t/index24.jpg",
  },
  {
    name_en: "",
    name_th: "นาย ภราดร ทองเสน",
    educate: "",
    posi: "ช่างเทคนิค ชำนาญงาน [ หัวหน้างานกายภาพและเทคโนโลยีดิจิทัล ]",
    major : "",
    dept : "",
    article: 0,
    project: 0,
    award: 0,
    img: "../img/t/index25.jpg",
  },
  // {
  //   name_en: "",
  //   name_th: "กันตภณ ธนกิจกร",
  //   educate: "ปริญญาเอก",
  //   posi: "ผู้ช่วยศาสตราจารย์",
  //   major : "วิศวกรรมต่อเรือและวิศวกรรมสมุทรศาสตร์",
  //   dept : "วิศวกรรมต่อเรือและวิศวกรรมสมุทรศาสตร์",
  //   article: 3,
  //   project: 3,
  //   award: 0,
  //   img: "testimonial-3.jpg",
  // },
  // {
  //   name_en: "",
  //   name_th: "รัฐกฤต เรียบร้อย",
  //   educate: "ปริญญาเอก",
  //   posi: "ผู้ช่วยศาสตราจารย์",
  //   major : "วิศวกรรมต่อเรือและวิศวกรรมสมุทรศาสตร์",
  //   dept : "วิศวกรรมต่อเรือและวิศวกรรมสมุทรศาสตร์",
  //   article: 3,
  //   project: 3,
  //   award: 0,
  //   img: "testimonial-2.jpg",
  // },
  // {
  //   name_en: "",
  //   name_th: "ศิริรัตน์ จึงรุ่งเรืองถาวร",
  //   educate: "ปริญญาเอก",
  //   posi: "ผู้ช่วยศาสตราจารย์",
  //   major : "วิศวกรรมต่อเรือและวิศวกรรมสมุทรศาสตร์",
  //   dept : "วิศวกรรมต่อเรือและวิศวกรรมสมุทรศาสตร์",
  //   article: 3,
  //   project: 3,
  //   award: 0,
  //   img: "testimonial-1.jpg",
  // },
  // {
  //   name_en: "",
  //   name_th: "ธีร์ เชาวนนทปัญญา",
  //   educate: "ปริญญาเอก",
  //   posi: "รองศาสตราจารย์",
  //   major : "วิศวกรรมต่อเรือและวิศวกรรมสมุทรศาสตร์",
  //   dept : "วิศวกรรมต่อเรือและวิศวกรรมสมุทรศาสตร์",
  //   article: 3,
  //   project: 3,
  //   award: 0,
  //   img: "testimonial-2.jpg",
  // },
  // {
  //   name_en: "",
  //   name_th: "มานิตย์ ลีกิจวัฒนะ",
  //   educate: "ปริญญาเอก",
  //   posi: "รองศาสตราจารย์",
  //   major : "วิศวกรรมต่อเรือและวิศวกรรมสมุทรศาสตร์",
  //   dept : "วิศวกรรมต่อเรือและวิศวกรรมสมุทรศาสตร์",
  //   article: 3,
  //   project: 3,
  //   award: 0,
  //   img: "testimonial-2.jpg",
  // },
  // {
  //   name_en: "",
  //   name_th: "ไพรีพินาศ พิมพิสาร",
  //   educate: "ปริญญาเอก",
  //   posi: "",
  //   major : "วิศวกรรมต่อเรือและวิศวกรรมสมุทรศาสตร์",
  //   dept : "วิศวกรรมต่อเรือและวิศวกรรมสมุทรศาสตร์",
  //   article: 3,
  //   project: 3,
  //   award: 0,
  //   img: "testimonial-2.jpg",
  // },
  // {
  //   name_en: "",
  //   name_th: "ศิวกร สุขประเสริฐชัย",
  //   educate: "ปริญญาโท",
  //   posi: "",
  //   major : "วิศวกรรมต่อเรือและวิศวกรรมสมุทรศาสตร์",
  //   dept : "วิศวกรรมต่อเรือและวิศวกรรมสมุทรศาสตร์",
  //   article: 3,
  //   project: 3,
  //   award: 0,
  //   img: "testimonial-2.jpg",
  // },
  // {
  //   name_en: "",
  //   name_th: "กิตติพศ โลกศุภไพบูลย์",
  //   educate: "ปริญญาเอก",
  //   posi: "",
  //   major : "วิศวกรรมต่อเรือและวิศวกรรมสมุทรศาสตร์",
  //   dept : "วิศวกรรมต่อเรือและวิศวกรรมสมุทรศาสตร์",
  //   article: 3,
  //   project: 3,
  //   award: 0,
  //   img: "testimonial-2.jpg",
  // },
  // {
  //   name_en: "",
  //   name_th: "เชิดวงศ์ แสงศุภาวนิช",
  //   educate: "ปริญญาเอก",
  //   posi: "ศาสตราจารย์",
  //   major : "วิทยาการเดินเรือและโลจิสติกส์ทางทะเล",
  //   dept: "วิทยาศาสตร์การเดินเรือ",
  //   article: 3,
  //   project: 3,
  //   award: 0,
  //   img: "testimonial-2.jpg",
  // },
  // {
  //   name_en: "",
  //   name_th: "พรรณศักดิ์ เอี่ยมรักษา",
  //   educate: "ปริญญาเอก",
  //   posi: "ผู้ช่วยศาสตราจารย์",
  //   major : "วิทยาการเดินเรือและโลจิสติกส์ทางทะเล",
  //   dept: "วิทยาศาสตร์การเดินเรือ",
  //   article: 3,
  //   project: 3,
  //   award: 0,
  //   img: "testimonial-2.jpg",
  // },
  // {
  //   name_en: "",
  //   name_th: "วัลลีย์ นวมมุสิก",
  //   educate: "ปริญญาเอก",
  //   posi: "ผู้ช่วยศาสตราจารย์",
  //   major : "วิทยาการเดินเรือและโลจิสติกส์ทางทะเล",
  //   dept: "วิทยาศาสตร์การเดินเรือ",
  //   article: 3,
  //   project: 3,
  //   award: 0,
  //   img: "testimonial-2.jpg",
  // },
  // {
  //   name_en: "",
  //   name_th: "แพรวพรรณ ออเรืองเอก",
  //   educate: "ปริญญาเอก",
  //   posi: "ผู้ช่วยศาสตราจารย์",
  //   major : "วิทยาการเดินเรือและโลจิสติกส์ทางทะเล",
  //   dept: "วิทยาศาสตร์การเดินเรือ",
  //   article: 0,
  //   project: 0,
  //   award: 0,
  //   img: "testimonial-4.jpg",
  // },
];
//  (${val.dept}) // 
var content = ``;
researcherList.forEach(function (val) {
  content += `<div class="default-card">
        <div class="d-flex align-items-center wow fadeInUp"
      data-wow-delay="0.2s">
          <img
            class="img-fluid flex-shrink-0 rounded wow fadeInUp"
      data-wow-delay="0.3s"
            src="img/${val.img}"
            style="width: 180px; height: 180px;"
          />
          <div class="ps-3" style="line-height: 1;">
            <h5 class="mb-1">${val.name_th}</h5>
            <div class="mb-2 txt-normal-xs">${val.major}</div>
            <button  type="button" class="btn btn-primary btn-sm">
              <span class="capitalize">research articles</span>
              <span class="badge txt-normal-xs " style="background-color: #ffffff5c;">${val.article}</span>
            </button>
            <button  type="button" class="btn btn-primary btn-sm">
              <span class="capitalize">research project</span>
              <span class="badge txt-normal-xs " style="background-color: #ffffff5c;">${val.project}</span>
            </button>
            <button  type="button" class="btn btn-primary btn-sm">
              <span class="capitalize">awards</span>
              <span class="badge txt-normal-xs " style="background-color: #ffffff5c;">${val.award}</span>
            </button>
          </div>
        </div>
      </div> `;
});
document.getElementsByClassName("researcherLists")[0].innerHTML = content;
